=== adiwg/mdKeywords/resources/schema/thesaurus-config.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "thesaurus-config.json#",
  "type": "object",
  "title": "Thesaurus Configuration",
  "description": "Configuration for thesauri",
  "required": ["citation", "label"],
  "oneOf": [
    {
      "required": ["keywords"]
    },
    {
      "required": ["keywordsUrl"]
    }
  ],
  "additionalProperties": true,
  "properties": {
    "citation": {
      "type": "object",
      "title": "citation",
      "description": "",
      "required": ["description", "title"],
      "additionalProperties": true,
      "properties": {
        "date": {
          "type": "array",
          "description": "Array of dates",
          "items": {
            "type": "object",
            "required": ["date", "dateType"],
            "additionalProperties": true,
            "properties": {
              "date": {
                "type": "string",
                "description": "An ISO 8601 date/timestamp.",
                "pattern": "^(\\d{4}(-\\d{2}(-\\d{2})?)?)$|^(\\d{4}-\\d{2}-\\d{2}(T\\d{2}:\\d{2}(:\\d{2}(\\.\\d+)?)?(Z|([+-]\\d{2}:\\d{2}))?)?)$"
              },
              "dateType": {
                "type": "string",
                "description": "The type of date. iso_dateType",
                "enum": [
                  "creation",
                  "publication",
                  "revision",
                  "expiry",
                  "lastUpdate",
                  "lastRevision",
                  "nextUpdate",
                  "unavailable",
                  "inForce",
                  "adopted",
                  "deprecated",
                  "superseded",
                  "validityBegins",
                  "validityExpires",
                  "released",
                  "distribution",
                  "acquisition",
                  "assessment",
                  "award",
                  "collected",
                  "due",
                  "end",
                  "received",
                  "reported",
                  "start",
                  "transmitted"
                ]
              },
              "description": {
                "type": "string"
              }
            }
          }
        },
        "description": {
          "type": "string",
          "description": "Thesaurus description"
        },
        "title": {
          "type": "string",
          "description": "Full name of the thesaurus"
        },
        "edition": {
          "type": "string",
          "description": "The version of the thesaurus"
        },
        "onlineResource": {
          "type": "array",
          "description": "Array of online resources",
          "items": {
            "type": "object",
            "required": ["uri"],
            "additionalProperties": false,
            "properties": {
              "uri": {
                "type": "string",
                "description": "URL to the source of the thesaurus"
              }
            }
          }
        },
        "identifier": {
          "type": "array",
          "description": "Array of identifiers",
          "items": {
            "type": "object",
            "required": ["identifier"],
            "additionalProperties": false,
            "properties": {
              "identifier": {
                "type": "string",
                "description": "Identifier for the thesaurus"
              }
            }
          }
        }
      }
    },
    "keywordType": {
      "type": "string",
      "description": "",
      "enum": [
        "discipline",
        "place",
        "stratum",
        "temporal",
        "theme",
        "dataCentre",
        "featureType",
        "instrument",
        "platform",
        "process",
        "project",
        "service",
        "product",
        "subTopicCategory",
        "taxon",
        "region",
        "isoTopicCategory",
        "methodology"
      ]
    },
    "label": {
      "type": "string",
      "description": "Short name for the thesaurus"
    },
    "keywords": {
      "type": "array",
      "description": "Array of keywords",
      "$ref": "./keyword.json#"
    },
    "keywordsUrl": {
      "type": "string",
      "format": "uri",
      "description": "URL to keywords file in resources/keywords/ directory."
    }
  }
}

=== adiwg/mdKeywords/resources/citations/gcmd-5b98265f-7cd1-4976-bc78-1ac1e6b9b90f.json
{
  "citation": {
    "date": [
      {
        "date": "2023-08-18 07:57:13",
        "dateType": "revision"
      }
    ],
    "description": "No description available.",
    "title": "Global Change Master Directory (GCMD) Disciplines",
    "edition": "Version 16.8",
    "onlineResource": [
      {
        "uri": "https://gcmd.earthdata.nasa.gov/kms/concept/5b98265f-7cd1-4976-bc78-1ac1e6b9b90f?format=json}"
      }
    ],
    "identifier": [
      {
        "identifier": "5b98265f-7cd1-4976-bc78-1ac1e6b9b90f"
      }
    ]
  },
  "keywordType": "discipline",
  "label": "Disciplines",
  "keywords": []
}
